name: bf2kernel
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Simon Binder <oss@simonbinder.eu>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  cli_util: ^0.1.3
  path: ^1.6.0
  kernel: 0.3.29 # We have to use a fixed kernel version. This one supports the 2.7 stable SDK
  # We don't even use the frontend, but pkg:kernel does without depending on it (shame!)
  front_end:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
